#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def parse_emcvnxe_dae(info):
    parsed = [dict(zip([t.replace('"', '') for t in info[0]], [s.replace('"', '') for s in c])) for c in info[1:]]
    return parsed

def inventory_emcvnxe_dae(parsed):
    for element in parsed:
        yield ( element.get('ID'), {})

def check_emcvnxe_dae(item, params, parsed):
    for element in parsed:
        if element.get('ID') == item:
            health = element.get('Health state')
            health_state = health.split(' ')[:1]
            if health_state[0] == "OK":
                state = 0
            else:
                state = 1
            return state, ("DAE Health State is %s" % health_state[0])

    return 3, ("DAE not found in agent output")

check_info["emcvnxe_dae"] = {
    "parse_function"        : parse_emcvnxe_dae,
    "check_function"        : check_emcvnxe_dae,
    "inventory_function"    : inventory_emcvnxe_dae,
    "service_description"   : "EMC DAE %s",
    "has_perfdata"          : False,
}

