#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def parse_prism_remote_support(info):
    import ast
    parsed = {}
    parsed = ast.literal_eval(info[0][0])
    return parsed


def check_prism_remote_support(_no_item, _no_params, parsed):
    state = 0
    msg_text = ""
    global_state = parsed["enable"].get("enabled", False)
    if global_state:
        return 1, "Remote Tunnel is enabled(!)"
    else:
        return 0, "Remote Tunnel is disabled"


check_info["prism_remote_support"] = {
    "parse_function": parse_prism_remote_support,
    "check_function": check_prism_remote_support,
    "inventory_function": discover_single,
    "has_perfdata": False,
    "service_description": "NTNX Remote Tunnel",
}
