#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def parse_prism_hosts(info):
    import ast
    parsed = {}
    data = ast.literal_eval(info[0][0])
    for element in data.get("entities"):
        parsed.setdefault(element.get("name", "unknown"), element)
    return parsed


@get_parsed_item_data
def check_prism_hosts(item, _no_params, data):
    state = 0
    state_text = data["state"]
    num_vms = data["numVMs"]
    memory = get_bytes_human_readable(data["memoryCapacityInBytes"])
    boottime = int(data["bootTimeInUsecs"]/ 1000 / 1000)
    uptime = time.strftime("%c", time.localtime(boottime))
    if state_text != "NORMAL":
        state = 1
    
    return state, "has state %s - Number of VMs %s - Memory %s - Boottime %s" % (state_text, num_vms, memory, uptime)


check_info["prism_hosts"] = {
    "parse_function": parse_prism_hosts,
    "check_function": check_prism_hosts,
    "inventory_function": discover(),
    "has_perfdata": False,
    "service_description": "Host %s",
}
