#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def parse_prism_hw_disks(info):
    import ast
    parsed = {}
    parsed = ast.literal_eval(info[0][0])
    return parsed


@get_parsed_item_data
def check_prism_hw_disks(item, _no_params, data):
    state = 0
    faulty = data["bad"]
    model = data["model"]
    serial = data["serialNumber"]
    mounted = data["mounted"]
    msg_txt = "Model: %s - Serial: %s - State: " % (model, serial)

    if faulty:
        state = 1
        msg_txt += "unhealthy"
    else:
        msg_txt += "healthy"
    
    if mounted:
        msg_txt += " - disk is mounted"
    else:
        msg_txt += " - disk is not mounted"
    
    return state, msg_txt


check_info["prism_hw_disks"] = {
    "parse_function": parse_prism_hw_disks,
    "check_function": check_prism_hw_disks,
    "inventory_function": discover(),
    "has_perfdata": False,
    "service_description": "NTX HW Disk %s",
}
