#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def parse_prism_vm_tools(info):
    import ast
    parsed = {}
    parsed = ast.literal_eval(info[0][0])
    return parsed


def check_prism_vm_tools(_no_item, _no_params, parsed):
    state = 0
    msg_text = ""
    tool_install = parsed["installedVersion"]
    tool_enabled = parsed["enabled"]
    
    if tool_install == None:
        msg_text += "No Tools installed"
    else:
        msg_text += "Tools with version %s installed" % tool_install
        if tool_enabled == False:
            state = 1
            msg_text += " but not enabled"
    
    return state, msg_text 


check_info["prism_vm_tools"] = {
    "parse_function": parse_prism_vm_tools,
    "check_function": check_prism_vm_tools,
    "inventory_function": discover_single,
    "has_perfdata": False,
    "service_description": "NTX VMTools",
}
