#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2020 
# Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<ilo_api_mem:sep(124)>>>
#proc1dimm1|DDR4|32768|OK
#Name | Type | SizeMB | Health

def inventory_ilo_api_mem(info):
    for line in info:
        yield line[0], None

def check_ilo_api_mem(item, _no_params, info):
    for line in info:
        if line[0] == item:
            if line[3] == "GoodInUse" or "OK":
                yield 0, u"Operational state OK - Type %s - Size %s MB" % (line[1], line[2])
            else:
                yield 2, u"Error in Modul %s with Status %s" % (line[0], line[3])

check_info["ilo_api_mem"] = {
    'check_function'      : check_ilo_api_mem,
    'inventory_function'  : inventory_ilo_api_mem,
    'has_perfdata'        : False,
    'service_description' : 'HW Mem %s',
}


