#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<ilo_api_mem>>>
#proc1dimm9 DDR4 8192 GoodInUse
#proc1dimm12 DDR4 8192 GoodInUse

def inventory_ilo_api_mem(info):
    for line in info:
        yield line[0], None

def check_ilo_api_mem(item, _no_params, info):
    for line in info:
        if line[0] == item:
            if line[3] == "GoodInUse":
                yield 0, u"Operational state OK - Type %s - Size %s MB" % (line[1], line[2])
            else:
                yield 2, u"Error in Modul %s with Status %s" % (line[0], line[3])

check_info["ilo_api_mem"] = {
    'check_function'      : check_ilo_api_mem,
    'inventory_function'  : inventory_ilo_api_mem,
    'has_perfdata'        : False,
    'service_description' : 'HW Mem %s',
}


