#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<ilo_api_general>>>
#ProLiant_DL360_Gen9 P89_v1.40_(05/06/2015) CZJ5290G1L OK

def inventory_ilo_api_general(info):
    for line in info:
        yield None, None

def check_ilo_api_general(item, _no_params, info):
    for line in info:
        if line[3] == "OK":
            yield 0, u"Operational state OK - %s - BIOS %s -  Serial %s" % (line[0].replace("_"," "), line[1].replace("_"," "), line[2])
        else:
            yield 2, u"Error in System with Status %s" % line[3]

check_info["ilo_api_general"] = {
    'check_function'      : check_ilo_api_general,
    'inventory_function'  : inventory_ilo_api_general,
    'has_perfdata'        : False,
    'service_description' : 'General Status',

}

