#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inventory_dell_compellent_encl(info):
    return [ (entry[0], None) for entry
              in info if entry[0] != None]

def check_dell_compellent_encl( item, _no_params, info):

    state_table = {
        "1" : ( "up, ", 0 ),
        "2" : ( "down, ", 2 ),
        "3" : ( "degraded", 1 ),
    }

    for descr, status, name, type, model in info:
        if item == descr:
            infotext, state = state_table.get(status, ("unknown state", 2 ))
            infotext = "Status: %s - %s - Model: %s - Typ: %s" % (infotext, name, model, type)
            return state, infotext
    return 3, "unknown"

check_info["dell_compellent_encl"] = {
    "check_function"        : check_dell_compellent_encl,
    "inventory_function"    : inventory_dell_compellent_encl,
    "service_description"   : "Enclosure Status",
    "has_perfdata"          : False,
    "snmp_info"             : ( ".1.3.6.1.4.1.16139.2.15.1", [
                                      OID_END,
                                      3, # scEnclStatus
                                      4, # scEnclName
                                      6, # scEnclType
                                      7, # scEnclModel
                              ]),
    "snmp_scan_function"    : lambda oid: oid('.1.3.6.1.4.1.16139.2.3.0') == "Dell-Compellent Technologies",
}
