#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# made for a windows plugin deployment


def bake_win_CHECKNAME(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(omd_root + "/local/share/check_mk/agents/windows/plugins/CHECKNAME.ps1",
                     plugins_dir + "/CHECKNAME.ps1")


bakery_info["win_CHECKNAME"] = {
    "bake_function": bake_win_CHECKNAME,
    "os": ["windows"],
}
