#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

factory_settings["<checkname>_default_levels"] = {
    "levels" : (55, 60),
}

def inventory_<checkname>(info):
    for line in info:
        yield line[0], {}

def check_<checkname>(item, params, info):
    if type(params) == tuple:
        params = { "levels" : params}
    # Only upper values are checked here - if also lower values
    # should be checked then a little bit more code is necessary
    warn, crit = params["levels"]
    
    for line in info:
        if line[0] == item:
            itemvalue = safeint(line[1])
            message = "Item at %d" % itemvalue
            perdata = [ ("item", itemvalue, warn, crit) ]
            if itemvalue > crit:
                message += "(!!)"
                return 2, message, perfdata
            elif itemvalue > warn:
                message += "(!)"
                return 1, message, perfdata
            else:
                return 0, message, perfdata
    return 3, "Item not found in agent output"

check_info["<checkname>"] = {
    "check_function"         : check_<checkname>,
    "inventory_function"     : inventory_<checkname>,
    "service_description"    : "<Itemname> %s",
    "default_levels_variable": "<checkname>_default_levels",
    "has_perfdata"           : True,                    # optional if available
    "group"                  : "<wato_group>",
    "snmp_scan_function"     : lambda oid: "<specific OID>" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info"              : ( "<target OID>", [ 1,   # suboid number one inside table
                                                   2,   # suboid number two inside table
                               ]),
}
