#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_hyperv_vms_guestinfos(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2( cmk.utils.paths.local_agents_dir + "/windows/plugins/hyperv_host.ps1",
                     plugins_dir + "/hyperv_host.ps1")

bakery_info["hyperv_vms_guestinfos"] = {
    "bake_function" : bake_hyperv_vms_guestinfos,
    "os"            : [ "windows" ],
}
