#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Andreas Doehler <andreas.doehler@bechtle.com>
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

ups_socomec_states = {
    1: "unknown",
    2: "Battery Normal",
    3: "Battery Low",
    4: "Battery Depleted",
    5: "Battery Discharging",
    6: "Battery Failure",
    7: "UPS Off",
}

def inventory_ups_socomec_status(info):
    if len(info) > 0:
        return [ (None, None) ]

def check_ups_socomec_status(item, params, info):
    status = saveint(info[0][0])
    seconds = saveint(info[0][1])
    runtime = saveint(info[0][2])
    capacity = saveint(info[0][3])
    voltage = saveint(info[0][4]) * 0.1
    temp = saveint(info[0][5])
    statename = ups_socomec_states.get(status, "(invalid)")
    if status == 2:
        return(0, "Status ist %s mit %d%% runtime remaining, Battery Voltage %sV" % (statename, runtime, voltage))
    else:
        return(2, "Status ist %s mit %d runtime remaining, Battery Voltage %sV" % (statename, runtime, voltage))

check_info['ups_socomec_status'] = {
  "inventory_function"  : inventory_ups_socomec_status,
  "check_function"      : check_ups_socomec_status,
  "service_description" : "Enviroment",
  "has_perfdata"        : True,
  "group"               : "socomec_status",
  "snmp_info"           : ( ".1.3.6.1.4.1.4555.1.1.1.1.2", [ "1", "2", "3", "4", "5", "6" ]),
  "snmp_scan_function"  : lambda oid: oid(".1.3.6.1.2.1.1.2.0") in [".1.3.6.1.4.1.4555.1.1.1"]

}
