#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def inv_snmp_hp_firmware(info):
    node = inv_tree_list("hardware.firmware:")
    if len(info) >= 1:
        for x in info:
            node.append({
                "component" : x[1],
                "version"   : x[2],
            })
    return node

inv_info['snmp_hp_firmware'] = {
    'inv_function'       : inv_snmp_hp_firmware,
    'snmp_info'          : ('.1.3.6.1.4.1.232.11.2.14.1.1', [
                                "1",   # index
                                "4",   # component name
                                "5",   # firmware version
                            ]),
    'snmp_scan_function'    : lambda oid: "8072.3.2.10" in oid(".1.3.6.1.2.1.1.2.0") or \
                                         (".1.3.6.1.4.1.232.9.4.10" in oid(".1.3.6.1.2.1.1.2.0")) or \
                                         (".1.3.6.1.4.1.311.1.1.3.1.2" in oid(".1.3.6.1.2.1.1.2.0") and \
                                          oid(".1.3.6.1.4.1.232.11.1.3.0")),
}

