#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_dellpowervault_arguments(params, hostname, ipaddress):
    args = ''
    if params["user"] != "":
        args += " -u " + quote_shell_string(params["user"])
    if params["password"] != "":
        args += " -p " + quote_shell_string(params["password"])

    args += " " + quote_shell_string(ipaddress)
    return args

special_agent_info['dellpowervault'] = agent_dellpowervault_arguments
