#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

@get_parsed_item_data
def check_dell_powervault_me4_controller_statistics(item, params, data):
    iops = data.get("iops")
    bytespersecond = data.get("bytes-per-second-numeric")
    data_read = data.get("data-read")
    data_write = data.get("data-written")
    perfdata = [("iops",iops),("bytes",bytespersecond)]
    message = "Written data %s and read data %s, IOPS %s/s, Bytes %s/s" % (data_write, data_read, iops, get_bytes_human_readable(bytespersecond))
    return 0, message, perfdata


check_info["dell_powervault_me4_controller-statistics"] = {
    "check_function": check_dell_powervault_me4_controller_statistics,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "Controller Stats %s",
    "has_perfdata": True,  # optional if available
    "includes": ["dell_powervault_me4.include"],
}
