#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

@get_parsed_item_data
def check_dell_powervault_me4_frus(item, params, data):
    fru_states = {
        0: ("Invalid Data", 3),
        1: ("Fault", 2),
        2: ("Absent", 0),
        3: ("Power Off", 1),
        4: ("OK", 0),
        5: ("N/A", 0),
    }

    state_text, status_num = fru_states.get(data.get("fru-status-numeric", 5), ("N/A", 0))
    message = "%s state is %s" % (data.get("description", "Unknown"), state_text)
    return status_num, message


check_info["dell_powervault_me4_frus"] = {
    "check_function": check_dell_powervault_me4_frus,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "Fru %s",
    "includes": ["dell_powervault_me4.include"],
}

