#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#


@get_parsed_item_data
def check_dell_powervault_me4_volume_statistics(item, params, data):
    sas_percent = data.get("percent-tier-sas")
    sata_percent = data.get("percent-tier-sata")
    ssd_percent = data.get("percent-tier-ssd")
    iops = data.get("iops")
    bytespersecond = data.get("bytes-per-second-numeric")

    perfdata = [("ssd_usage",ssd_percent),("sas_usage",sas_percent),("sata_usage",sata_percent),("iops",iops),("bytes",bytespersecond)]
    message = "Usage SSD: %s%%, SAS %s%%, SATA %s%%, IOPS %s/s, Bytes %s/s" % (ssd_percent, sas_percent, sata_percent, iops, get_bytes_human_readable(bytespersecond))
    return 0, message, perfdata


check_info["dell_powervault_me4_volume-statistics"] = {
    "check_function": check_dell_powervault_me4_volume_statistics,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "Volume Stats %s",
    "has_perfdata": True,  # optional if available
    "includes": ["dell_powervault_me4.include"],
    "group": "dell_volume",
}
