#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

@get_parsed_item_data
def check_dell_powervault_me4_volumes(item, params, data):
    vol_states = {
        0: ("OK", 0),
        1: ("Degraded", 1),
        2: ("Fault", 2),
        3: ("Unknown", 3),
    }

    state_text, status_num  = vol_states.get(data.get("health-numeric", 3), ("Unknown",3))
    message = "%s with %s total size is %s" % (data.get("volume-name"), data.get("total-size"), state_text)
    return status_num, message


check_info["dell_powervault_me4_volumes"] = {
    "check_function": check_dell_powervault_me4_volumes,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "Volume %s",
    "has_perfdata": True,  # optional if available
    "includes": ["dell_powervault_me4.include"],
}
