#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

@get_parsed_item_data
def check_dell_powervault_me4_pools(item, params, data):
    pool_states = {
        0: ("OK", 0),
        1: ("Degraded", 1),
        2: ("Fault", 2),
        3: ("Unknown", 3),
    }

    state_text, status_num  = pool_states.get(data.get("health-numeric", 3), ("Unknown",3))
    message = "Pool %s with %s total size is %s, available capacity %s" % (data.get("name"), data.get("total-size"), state_text, data.get("total-avail"))
    return status_num, message


check_info["dell_powervault_me4_pools"] = {
    "check_function": check_dell_powervault_me4_pools,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "Pool %s",
    "has_perfdata": True,  # optional if available
    "includes": ["dell_powervault_me4.include"],
}
