#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

@get_parsed_item_data
def check_dell_powervault_me4_power_supplies(item, params, data):
    psu_states = {
        0: ("OK", 0),
        1: ("Degraded", 1),
        2: ("Fault", 2),
        3: ("Unknown", 3),
    }

    state_text, status_num  = psu_states.get(data.get("health-numeric", 3), ("Unknown",3))
    message = "%s state is %s" % (data.get("description", "Unknown"), state_text)
    return status_num, message


check_info["dell_powervault_me4_power-supplies"] = {
    "check_function": check_dell_powervault_me4_power_supplies,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "PSU %s",
    "has_perfdata": True,  # optional if available
    "includes": ["dell_powervault_me4.include"],
}
