#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#

@get_parsed_item_data
def check_dell_powervault_me4_fans(item, params, data):
    fan_states = {
        0: ("OK", 0),
        1: ("Degraded", 1),
        2: ("Fault", 2),
        3: ("Unknown", 3),
    }

    state_text, status_num  = fan_states.get(data.get("health-numeric", 3), ("Unknown",3))
    perfdata = [("fan", data.get("speed"))]
    message = "%s %s is %s with speed %s rpm" % (data.get("name"), data.get("location", "Unknown"), state_text, data.get("speed"))
    return status_num, message, perfdata


check_info["dell_powervault_me4_fans"] = {
    "check_function": check_dell_powervault_me4_fans,
    "parse_function": parse_dell_powervault_me4,
    "inventory_function": discover(),
    "service_description": "Fan %s",
    "has_perfdata": True,
    "includes": ["dell_powervault_me4.include"],
}
