#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# made for a windows plugin deployment

def bake_win_<checkname>(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2( omd_root + "/local/share/check_mk/agents/windows/plugins/<checkname>.ps1",
                     plugins_dir + "/<checkname>.ps1")

bakery_info["win_<checkname>"] = {
    "bake_function" : bake_win_<checkname>,
    "os"            : [ "windows" ],
}
