#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def agent_ilo_arguments(params, hostname, ipaddress):
    args = []

    args += ["--user=%s" % params["user"]]
    args += [passwordstore_get_cmdline("--password=%s", params["password"])]

    args.append(ipaddress)

    return args


special_agent_info['ilo'] = agent_ilo_arguments

