#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2020 
# Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<ilo_api_general:sep(124)>>>
#ProLiant DL380 Gen10|U30 v2.04 (04/18/2019)|CZ123456789|OK
#Server Typ | BIOS Ver. | Serial | Health

def inventory_ilo_api_general(info):
    for line in info:
        yield None, None

def check_ilo_api_general(_no_item, _no_params, info):
    for line in info:
        if line[3] == "OK":
            yield 0, u"Operational state OK - %s - BIOS %s -  Serial %s" % (line[0].replace("_"," "), line[1].replace("_"," "), line[2])
        elif line[3] == "Warning":
            yield 1, u"Operational state Warning - %s - BIOS %s -  Serial %s" % (line[0].replace("_"," "), line[1].replace("_"," "), line[2])
        else:
            yield 2, u"Error in System with Status %s" % line[3]

check_info["ilo_api_general"] = {
    'check_function'      : check_ilo_api_general,
    'inventory_function'  : inventory_ilo_api_general,
    'has_perfdata'        : False,
    'service_description' : 'General Status',

}
