#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) 2020 
# Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  This file is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

#<<<ilo_api_raid:sep(124)>>>
#0-1|1|228902|262144|OK
#Nr. | Raidlevel | SizeMB | BlocksizekB | Status

def inventory_ilo_api_raid(info):
    for line in info:
        yield line[0], None

def check_ilo_api_raid(item, _no_params, info):
    for line in info:
        if line[0] == item:
            if line[4] == "OK":
                yield 0, u"Operational state OK - Raid %s - Size %s GB - Sector Size %s kB" % (line[1], int(line[2])/1024, int(line[3])/1024)
            elif line[4] == "Warning":
                yield 1, u"Operational state Warning - Raid %s - Size %s GB - Sector Size %s kB" % (line[1], int(line[2])/1024, int(line[3])/1024)
            else:
                yield 2, u"Error in Raid %s with Status %s" % (line[0], line[4])

check_info["ilo_api_raid"] = {
    'check_function'      : check_ilo_api_raid,
    'inventory_function'  : inventory_ilo_api_raid,
    'has_perfdata'        : False,
    'service_description' : 'Logical Drive %s',

}


