#!/usr/bin/env python3

# mypy: disable-error-code="list-item"

from typing import Any, Mapping, Optional, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


def agent_ilo_arguments(
        params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[str]:
    """build command line arguments"""
    return [
        "--server",
        ipaddress or hostname,
        "--user",
        f"{params['user']}",
        "--password",
        passwordstore_get_cmdline("%s", params["password"]),
        *(["-p", f"{params['port']}"] if "port" in params else []),
        *(["-P", f"{params['proto']}"] if "proto" in params else []),
    ]


special_agent_info["ilo"] = agent_ilo_arguments
