#!/usr/bin/env python3

# mypy: disable-error-code="list-item"

from typing import Any, Mapping, Optional, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


def agent_ilo_arguments(
        params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[str]:
    return [
        "--server",
        ipaddress or hostname,
        "--user",
        "%s" % params["user"],
        "--password",
        passwordstore_get_cmdline("%s", params["password"]),
    ]


special_agent_info["ilo"] = agent_ilo_arguments
