#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def inventory_lenovo_xcc_voltage(info):
    for line in info:
        yield line[0], None


def check_lenovo_xcc_voltage(item, no_params, info):
    lenovo_xcc_voltage_status_codes = {
        "Normal" : (0, "normal"),
    }

    for line in info:
        if line[0] == item:
            status, name = lenovo_xcc_voltage_status_codes.get(line[2], ("2", "not normal"))
            return status, u"Voltage status is %s with %sV" % (name, line[1])


check_info["lenovo_xcc_voltage"] = {
    "check_function": check_lenovo_xcc_voltage,
    "inventory_function": inventory_lenovo_xcc_voltage,
    "service_description": "Voltage %s",
    "snmp_scan_function": lambda oid: ".1.3.6.1.4.1.19046.11.1" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info": (
        ".1.3.6.1.4.1.19046.11.1.1.2.2.1",
        [
            2,  # voltDescr
            3,  # voltReading
            11, # voltHealthStatus
        ]),
}

