#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def inventory_lenovo_xcc_drive(info):
    for line in info:
        yield line[0], None


def check_lenovo_xcc_drive(item, no_params, info):
    lenovo_xcc_drive_status_codes = {
        "Normal" : (0, "normal"),
    }

    for line in info:
        if line[0] == item:
            status, name = lenovo_xcc_drive_status_codes.get(line[1], ("2", "not normal"))
            return status, u"Drive status is %s" % (name)


check_info["lenovo_xcc_drive"] = {
    "check_function": check_lenovo_xcc_drive,
    "inventory_function": inventory_lenovo_xcc_drive,
    "service_description": "%s",
    "snmp_scan_function": lambda oid: ".1.3.6.1.4.1.19046.11.1" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info": (
        ".1.3.6.1.4.1.19046.11.1.1.12.2.1",
        [
            2,  # diskFruName
            3,  # diskHealthStatus
        ]),
}

