#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def inventory_lenovo_xcc_fan(info):
    for line in info:
        yield line[0], None


def check_lenovo_xcc_fan(item, no_params, info):
    lenovo_xcc_fan_status_codes = {
        "Normal" : (0, "normal"),
    }

    for line in info:
        if line[0] == item:
            status, name = lenovo_xcc_fan_status_codes.get(line[2], ("2", "not normal"))
            return status, u"Fan status is %s with %s" % (name, line[1])


check_info["lenovo_xcc_fan"] = {
    "check_function": check_lenovo_xcc_fan,
    "inventory_function": inventory_lenovo_xcc_fan,
    "service_description": "%s",
    "snmp_scan_function": lambda oid: ".1.3.6.1.4.1.19046.11.1" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info": (
        ".1.3.6.1.4.1.19046.11.1.1.3.2.1",
        [
            2,  # fanDescr
            3,  # fanSpeed
            10, # fanHealthStatus
        ]),
}

