#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Sample agent output
# <<CHECKNAME>>
# checkstatus 0 with much text output


def inventory_CHECKNAME(info):
    return [(None, {})]


def check_CHECKNAME(_no_item, _no_params, info):
    CHECKNAME_status_codes = {
        0: (0, "ok"),
        1: (1, "warning"),
        2: (2, "critical"),
        3: (3, "unknown"),
    }

    # the following depends on the info - agent output is separeted at <space>
    status, name = CHECKNAME_status_codes[int(info[0][1])]
    messagetext = " ".join(info[0][2:])
    return status, "Item status: %s with message - %s" % (name, messagetext)


check_info["CHECKNAME"] = {
    "check_function": check_CHECKNAME,
    "inventory_function": inventory_CHECKNAME,
    "service_description": "<Itemname>",
}
