#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Example output from agent:
#<<<3par_node:sep(32)>>>
# 0 1687417-0 OK      Yes    Yes       Unknown      GreenBlnk   16384    8192          100
# 1 1687417-1 OK      No     Yes       Unknown      GreenBlnk   16384    8192          100

# The names of the columns are:
#                                                               Control    Data        Cache
#Node --Name--- -State- Master InCluster -Service_LED ---LED--- Mem(MB) Mem(MB) Available(%)

def inventory_3par_node(info):
    inventory = []
    for line in info:
        node_id = line[0] 
        inventory.append( (node_id, None) )
    return inventory

def check_3par_node(item, _no_params, info):
    for line in info:
        if line[0] == item:

            node_id, name, state, master, cluster, service_led, master_led, \
                control_mem, data_mem, cache = line

            # Check status
            message = "Node %s with name %s is %s" % ( node_id, name, state)
            if state == "OK":
                status = 0
            else:
                status = 2
                message += "(!!)"

            return status, message

    return 3, "Node %s not found in agent output" % item

check_info["3par_node"] = {
    "check_function"        : check_3par_node,
    "inventory_function"    : inventory_3par_node,
    "service_description"   : "Node %s",
    "has_perfdata"          : False,
}

