#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Example output from agent:
#<<<3par_cage:sep(32)>>>
# 0 1687417-0 OK      Yes    Yes       Unknown      GreenBlnk   16384    8192          100
# 1 1687417-1 OK      No     Yes       Unknown      GreenBlnk   16384    8192          100

# The names of the columns are:
#                                                               Control    Data        Cache
#Node --Name--- -State- Master InCluster -Service_LED ---LED--- Mem(MB) Mem(MB) Available(%)

def inventory_3par_cage(info):
    inventory = []
    for line in info:
        if len(line) == 12 and line[0].isdigit():
            inventory.append( (line[0], None) )
    return inventory

def check_3par_cage(item, params, info):
    for line in info:
        if line[0] == item:
            cage_id, name, loopa, posa, loopb, posb, drives, \
                temp, reva, revb, model, side = line
            temperatures = temp.split("-")
            state, infotext, perfdata = check_temperature(float(temperatures[1]), params, "3par_cage_temp_%s" % item)
            message = "Cage %s with %s Drives is Available - Maximum Temperature is %s" % ( cage_id, drives, infotext)
            return state, message, perfdata

    return 3, "Cage %s not found in agent output" % item

check_info["3par_cage"] = {
    "check_function"        : check_3par_cage,
    "inventory_function"    : inventory_3par_cage,
    "service_description"   : "Cage %s",
    "has_perfdata"          : True,
    "includes"              : [ "temperature.include" ],
    "group"                 : "temperature",
}

