#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# Example output from agent:
#<<<3par_ld>>>
#  0 admin.usr.0      1 normal           0/1     5120     5120 V       0  ---     N    Y
#  1 admin.usr.1      1 normal           1/0     5120     5120 V       0  ---     N    Y

# The names of the columns are:
# Id Name          RAID -Detailed_State- Own   SizeMB   UsedMB Use  Lgct LgId WThru MapV

def inventory_3par_ld(info):
    inventory = []
    for line in info:
        if len(line) == 12 and line[0].isdigit():
            ld_id = line[0].zfill(3)
            inventory.append( (ld_id, None) )
    return inventory

def check_3par_ld(item, _no_params, info):
    for line in info:
        if line[0].zfill(3) == item and len(line) == 12:

            ld_id, name, raid, state, owner, size_mb, \
                used_mb, useing, lgct, lgid, wthru, mapv = line
            # Check status
            message = "LD %s/%s (%s MB) RAID %s with status %s is owned by %s" % ( ld_id.zfill(3), name, size_mb, raid, state, owner)
            if state == "normal":
                status = 0
            else:
                status = 2
                message += "(!!)"

            return status, message

    return 3, "LD %s not found in agent output" % item

check_info["3par_ld"] = {
    "check_function"        : check_3par_ld,
    "inventory_function"    : inventory_3par_ld,
    "service_description"   : "LD %s",
    "has_perfdata"          : False,
}

