#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# This file is no offical part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def agent_3par_arguments(params, hostname, ipaddress):
    args = ''
    args += " -u " + quote_shell_string(params["user"])
    if params["accept-any-hostkey"] == True:
        args += " --accept-any-hostkey"
    args += " -i " + ",".join(params["infos"])

    args += " " + quote_shell_string(ipaddress)
    return args

special_agent_info['3par'] = agent_3par_arguments

