#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Example output from agent:
# <<<hyperv_disabletimesync>>>
# hostname1.domain.net        Zeitsynchronisierung False   OK                                                 
# hostname2.domain.net        Zeitsynchronisierung True   OK                                                 
# 

def inventory_hyperv_disabletimesync(info):
    if len(info) > 0:
        return [(None, None)]

def check_hyperv_disabletimesync(item, params, info):
    if len(info) == 0:
        return (3, "no information from Hyper-V")
    single_states = []
    for line in info:
        if line[2] in [ "True" ]:
            state = 1
            single_states.append( (state, line[0] ) )
        elif line[2] in [ "False" ]:
            state = 0
            single_states.append( (state, line[0] ) )
        else:
            state = 3
            single_states.append( (state, line[0] ) )

    worst_state = max([x[0] for x in single_states])
    if worst_state != 0:
        info_text = ", ".join([x[1] for x in single_states if x[0] != 0])
    else:
        info_text = "Alle Maschinen OK"
    return (worst_state, "Disabletimesync Status - %s" % info_text)
    

check_info["hyperv_disabletimesync"] = {
    "check_function"        : check_hyperv_disabletimesync,
    "group"                 : "windows_hyperv",
    "inventory_function"    : inventory_hyperv_disabletimesync,
    "service_description"   : "Hyper-V Disabletimesync",
    "has_perfdata"          : False,
}

