#!/usr/bin/python
# SMS (using SMS Gateway)
# Notification via sms using the SMS Gateway from https://github.com/b-s101/php-sms-gateway

import os, sys

send_path = None

max_len = 160
message = os.environ['NOTIFY_HOSTNAME'] + " "

if os.environ['NOTIFY_WHAT'] == 'SERVICE':
    message += os.environ['NOTIFY_SERVICESTATE'][:2] + " "
    avail_len = max_len - len(message)
    message += os.environ['NOTIFY_SERVICEDESC'][:avail_len] + " "
    avail_len = max_len - len(message)
    message += os.environ['NOTIFY_SERVICEOUTPUT'][:avail_len]

else:
    message += "is " + os.environ['NOTIFY_HOSTSTATE']

message = message.replace(" ","_")
empf = os.environ['NOTIFY_CONTACTPAGER']
os.system("curl -X Get 'http://smsgw.sbs-dresden.de/api/api.php?user=<username>&pw=<password>&text='%s'&dest=%s' % (message[:160], empf))