#!/usr/bin/env python3
"""Dell ME4 special agent command line generation"""

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>
# License: GNU General Public License v2

from typing import Any, Mapping, Optional, Sequence

from cmk.base.check_api import passwordstore_get_cmdline
from cmk.base.config import special_agent_info


def agent_dellpowervault_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[str]:
    """build command line arguments"""
    return [
        "-u",
        f"{params['user']}",
        "-p",
        passwordstore_get_cmdline("%s", params["password"]),
        ipaddress or hostname,
    ]


special_agent_info["dellpowervault"] = agent_dellpowervault_arguments
