{'svcproblems_notify': {'browser_reload': 30,
                        'column_headers': 'pergroup',
                        'datasource': 'services',
                        'description': u'All problems of services not currently in a downtime and with notification enabled.',
                        'force_checkboxes': False,
                        'group_painters': [('service_state', None, '')],
                        'hard_filters': ['summary_host',
                                         'service_notifications_enabled',
                                         'in_downtime'],
                        'hard_filtervars': [('is_service_acknowledged',
                                             '-1'),
                                            ('is_summary_host', '0'),
                                            ('hst0', 'on'),
                                            ('hst1', ''),
                                            ('hst2', ''),
                                            ('hstp', 'on'),
                                            ('st0', ''),
                                            ('st1', 'on'),
                                            ('st2', 'on'),
                                            ('st3', 'on'),
                                            ('stp', ''),
                                            ('is_service_in_notification_period',
                                             '-1'),
                                            ('hdst0', 'on'),
                                            ('hdst1', 'on'),
                                            ('hdst2', 'on'),
                                            ('hdst3', 'on'),
                                            ('hdstp', 'on'),
                                            ('service', ''),
                                            ('is_service_notifications_enabled',
                                             '1'),
                                            ('is_in_downtime', '0')],
                        'hidden': False,
                        'hide_filters': [],
                        'hidebutton': False,
                        'layout': 'table',
                        'linktitle': u'',
                        'mobile': False,
                        'mustsearch': False,
                        'name': 'svcproblems_notify',
                        'num_columns': 1,
                        'owner': 'nagiosadmin',
                        'painters': [('host', 'host', ''),
                                     ('service_description', 'service', ''),
                                     ('svc_plugin_output', None, ''),
                                     ('svc_state_age', None, ''),
                                     ('svc_check_age', None, ''),
                                     ('service_icons', None, ''),
                                     ('perfometer', None, '')],
                        'play_sounds': True,
                        'public': True,
                        'show_filters': ['service_acknowledged',
                                         'hoststate',
                                         'svcstate',
                                         'service_in_notification_period',
                                         'svchardstate',
                                         'serviceregex'],
                        'sorters': [('svcstate', True),
                                    ('stateage', False),
                                    ('svcdescr', False)],
                        'title': u'Service problems short',
                        'user_sortable': 'on'}}
