#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>
# License: GNU General Public License v2
from typing import Any, Mapping, Optional, Sequence

from cmk.base.config import special_agent_info


def agent_3par_ssh_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[str]:
    """build command line arguments"""
    return [
        "-u",
        f"{params['user']}",
        *(["--accept-any-hostkey"] if "accept-any-hostkey" in params else []),
        *(["-i", f"{','.join(params['infos'])}"] if "infos" in params else []),
        ipaddress or hostname,
    ]


special_agent_info['3par_ssh'] = agent_3par_ssh_arguments
