#!/usr/bin/env python3
'''special agent call file'''
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# License: GNU General Public License v2

import sys

from cmk_addons.plugins.dell_powervault_me4.special_agents.agent_dellpowervault import main

if __name__ == "__main__":
    sys.exit(main())
