#!/usr/bin/env python3
"""Dell ME4 special agent"""

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>
# License: GNU General Public License v2

import argparse
import hashlib
import sys

import cmk.utils.password_store
import requests
import urllib3
from cmk.special_agents.v0_unstable.agent_common import SectionWriter

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

cmk.utils.password_store.replace_passwords()

commands = (
    "controllers",
    "disks",
    "system",
    "sensor-status",
    "power-supplies",
    "frus",
    "fans",
    "volumes",
    "pools",
    "controller-statistics",
    "volume-statistics",
    "ports",
)


def parse_arguments(argv):
    """argument parser"""
    parser = argparse.ArgumentParser(description=__doc__)

    # flags
    parser.add_argument(
        "-v", "--verbose", action="count", help="""Increase verbosity"""
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="""Debug mode: let Python exceptions come through""",
    )

    parser.add_argument("hostaddress", help="DELL EMC PowerVault host name")
    parser.add_argument("-u", "--username", required=True, help="DELL EMC user name")
    parser.add_argument(
        "-p", "--password", required=True, help="DELL EMC user password"
    )

    args = parser.parse_args(argv)
    return args


def main(argv=None):
    """parse arguments and retrieve data from the device"""
    args = parse_arguments(argv or sys.argv[1:])

    url = "https://" + args.hostaddress
    auth_string = hashlib.sha256(
        f"{args.username}_{args.password}".encode("utf-8")
    ).hexdigest()

    s = requests.session()
    s.headers.update({"datatype": "json"})
    r = s.get(url + "/api/login/" + auth_string, verify=False, timeout=5)
    sessionkey = r.json()["status"][0]["response"]
    s.headers.update({"sessionKey": sessionkey})

    for element in commands:
        response = s.get(url + "/api/show/" + element, timeout=5)
        with SectionWriter(f"dell_powervault_me4_{element.replace('-', '_')}") as w:
            w.append_json(response.json())

    return 0


if __name__ == "__main__":
    sys.exit(main())
