#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# only useable with the
# .------------------------------------------------------------------------.
# |                ____ _               _        __  __ _  __              |
# |               / ___| |__   ___  ___| | __   |  \/  | |/ /              |
# |              | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /               |
# |              | |___| | | |  __/ (__|   <    | |  | | . \               |
# |               \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\              |
# |                                        |_____|                         |
# |             _____       _                       _                      |
# |            | ____|_ __ | |_ ___ _ __ _ __  _ __(_)___  ___             |
# |            |  _| | '_ \| __/ _ \ '__| '_ \| '__| / __|/ _ \            |
# |            | |___| | | | ||  __/ |  | |_) | |  | \__ \  __/            |
# |            |_____|_| |_|\__\___|_|  | .__/|_|  |_|___/\___|            |
# |                                     |_|                                |
# |                     _____    _ _ _   _                                 |
# |                    | ____|__| (_) |_(_) ___  _ __                      |
# |                    |  _| / _` | | __| |/ _ \| '_ \                     |
# |                    | |__| (_| | | |_| | (_) | | | |                    |
# |                    |_____\__,_|_|\__|_|\___/|_| |_|                    |
# |                                                                        |
# | mathias-kettner.com                                 mathias-kettner.de |
# '------------------------------------------------------------------------'

def bake_mssql(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(omd_root + "/local/share/check_mk/agents/windows/plugins/mssql.vbs",
                     plugins_dir + "/mssql.vbs")

    # convert old configuration (just enable/disable) to new dict params
    if conf == True:
        conf = {}

    def write_mssql_ini(path, auth):
        f = file(path, "w")
        f.write("[auth]\n")
        if auth == "system":
            f.write("type = system\n")
        else:
            f.write("type = db\n"
                    "username = %s\n"
                    "password = %s\n" % auth[1])

    write_mssql_ini(conf_dir + "/mssql.ini", conf.get("auth_default", "system"))

    for instance, auth_conf in conf.get("auth_instances", []):
        write_mssql_ini(conf_dir + "/mssql_%s.ini" % instance, auth_conf)


bakery_info["mssql"] = {
    "bake_function" : bake_mssql,
    "os"            : [ "windows" ],
}
