#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#################################################################
#	 _  _ ___ _____ _   ___ ___    ___ _  _ ___ ___ _  __	#
#	| \| | __|_   _/_\ | _ \ _ \  / __| || | __/ __| |/ /	#
#	| .` | _|  | |/ _ \|  _/  _/ | (__| __ | _| (__| ' <	#	
#	|_|\_|___| |_/_/ \_\_| |_|    \___|_||_|___\___|_|\_\	#		
#---------------------------------------------------------------#
# Author: Benjamin Odenthal					#
# Contact: support@tuxclouds.org				#
# File: netapp_ps						#
# Version: 1.0							#
# Revision: 14.Oct.2010						#
# Description: The purpose of this netapp_ps is to check	#
# the functionality of all Powersupplies via SNMP		#
# As Result you get the Number of failed Powersupplies		#
#################################################################
netapp_ps_default_levels = (1, 2)

def inventory_netapp_ps(checkname, info):
	inventory = [ ("Powersupplies Failed", "", "netapp_ps_default_levels") ]
	return inventory

def check_netapp_ps(item, params, info):
	warn, crit = params

	for line in info:
	     psdefect = int(line[0])
	if (psdefect == ""):
		return (3, "UNKNOWN - Check SNMP or OID")
	
	perfdata = [("powersupplies", psdefect, warn, crit)]

	if psdefect >= crit:
		return (2, "CRIT - NetAPP Powersupplies Failed: %d (critical at %d)" % (psdefect, crit), perfdata)
	elif psdefect >= warn:
		return (1, "WARN - NetAPP Powersupplies Failed: %d (warning at %d)" % (psdefect, warn), perfdata)
	else:
		return (0, "OK - NetAPP Powersupplies Failed: %d" % psdefect, perfdata)
	
check_info["netapp_ps"] = (check_netapp_ps, "NetApp", 1, inventory_netapp_ps)

snmp_info["netapp_ps"] = ( ".1.3.6.1.4.1.789.1.2.4", ["4"] )

snmp_scan_functions['netapp_ps'] = \
    lambda oid: oid("1.3.6.1.2.1.1.1.0").startswith('NetApp Release')
