#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#################################################################
#    _  _ ___ _____ _   ___ ___    ___ _  _ ___ ___ _  __       #
#   | \| | __|_   _/_\ | _ \ _ \  / __| || | __/ __| |/ /       #
#   | .` | _|  | |/ _ \|  _/  _/ | (__| __ | _| (__| ' <        #
#   |_|\_|___| |_/_/ \_\_| |_|    \___|_||_|___\___|_|\_\       #
#---------------------------------------------------------------#
# Author: Benjamin Odenthal                                     #
# Contact: support@tuxclouds.org                                #
# File: netapp_temp                                             #
# Version: 1.0                                                  #
# Revision: 14.Oct.2010                                         #
# Description: The purpose of this netapp_temp is to check      #
# the functionality of all Fans via SNMP                        #
# As Result you get the Number of failed Fans.                  #
################################################################

# .1.3.6.1.4.1.789.1.2.4.1 -> Over Temp

def inventory_netapp_temp(checkname, info):
    return [ (line[1]+" "+line[0], None) for line in info if line[1] <> '' ]

def check_netapp_temp(item, params, info):
    info = [ line for line in info if line[1]+" "+line[0] == item ]
    for line in info:
        shelftemp = str(line[3])
        shelferror = str(line[2]) 
    if (shelferror <> ""):
        return (2, "CRITICAL - NetAPP Temperatur: %s" % shelftemp,"")

#   perfdata = [("fans", fansdefect, warn, crit)]
    return (0, "OK - NetAPP Temperatur: %s" % shelftemp, "")

check_info["netapp_temp"] = {
    "check_function"        : check_netapp_temp,
    "inventory_function"    : inventory_netapp_temp,
    "service_description"   : "NetApp ShelfTemp %s",
    "has_perfdata"          : True,
    "group"                 : "netapp_temp",
    "snmp_scan_function"    : lambda oid: oid("1.3.6.1.2.1.1.1.0").startswith('NetApp Release'),
    "snmp_info"             : ( ".1.3.6.1.4.1.789.1.21.1.2.1", ["9","5","21","25"] )
}

