#!/usr/bin/python
# # -*- encoding: utf-8; py-indent-offset: 4 -*-

#.
#   .--Name----------------------------------------------------------------.
#   |                     _   _                                            |
#   |                    | \ | | __ _ _ __ ___   ___                       |
#   |                    |  \| |/ _` | '_ ` _ \ / _ \                      |
#   |                    | |\  | (_| | | | | | |  __/                      |
#   |                    |_| \_|\__,_|_| |_| |_|\___|                      |
#   |                                                                      |
#   '----------------------------------------------------------------------'
#   |                                                                      |
#   '----------------------------------------------------------------------'


def inventory_hyperv_vm_general_name(parsed):
    if 'name' in parsed:
        return [(None, None)]


def check_hyperv_vm_general_name(_no_item, _no_params, parsed):
    return (0, parsed['name'])


check_info['hyperv_vm_general'] = {
    "inventory_function": inventory_hyperv_vm_general_name,
    "check_function": check_hyperv_vm_general_name,
    "parse_function": hyperv_vm_convert,
    "includes": ["hyperv.include"],
    "service_description": "HyperV Name",
}

#.
#   .--Runtime Host--------------------------------------------------------.
#   |    ____              _   _                  _   _           _        |
#   |   |  _ \ _   _ _ __ | |_(_)_ __ ___   ___  | | | | ___  ___| |_      |
#   |   | |_) | | | | '_ \| __| | '_ ` _ \ / _ \ | |_| |/ _ \/ __| __|     |
#   |   |  _ <| |_| | | | | |_| | | | | | |  __/ |  _  | (_) \__ \ |_      |
#   |   |_| \_\\__,_|_| |_|\__|_|_| |_| |_|\___| |_| |_|\___/|___/\__|     |
#   |                                                                      |
#   +----------------------------------------------------------------------+
#   |                                                                      |
#   '----------------------------------------------------------------------'


def inventory_hyperv_vm_general_running_on(parsed):
    if 'runtime.host' in parsed:
        return [(None, None)]


def check_hyperv_vm_general_running_on(no_item, no_params, parsed):
    running_on = parsed.get("runtime.host")

    if not running_on:
        return 3, "Runtime host information is missing"

    return 0, "Running on %s" % running_on


check_info['hyperv_vm_general.running_on'] = {
    "inventory_function": inventory_hyperv_vm_general_running_on,
    "check_function": check_hyperv_vm_general_running_on,
    "service_description": "HyperV Hostsystem",
}

