#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

factory_settings["CHECKNAME_default_levels"] = {
    "levels": (55, 60),
}


def inventory_CHECKNAME(info):
    for line in info:
        yield line[0], {}


def check_CHECKNAME(item, params, info):
    if type(params) == tuple:
        params = {"levels": params}
    # Only upper values are checked here - if also lower values
    # should be checked then a little bit more code is necessary
    warn, crit = params["levels"]
    perfdata = []
    for line in info:
        if line[0] == item:
            itemvalue = saveint(line[1])
            message = "Item at %d" % itemvalue
            perfdata = [("item", itemvalue, warn, crit)]
            if itemvalue > crit:
                message += "(!!)"
                return 2, message, perfdata
            elif itemvalue > warn:
                message += "(!)"
                return 1, message, perfdata
            else:
                return 0, message, perfdata


check_info["CHECKNAME"] = {
    "check_function": check_CHECKNAME,
    "inventory_function": inventory_CHECKNAME,
    "service_description": "<Itemname> %s",
    "default_levels_variable": "CHECKNAME_default_levels",
    "has_perfdata": True,  # optional if available
    "group": "<wato_group>",
    "snmp_scan_function": lambda oid: "<specific OID>" in oid(".1.3.6.1.2.1.1.2.0"),
    "snmp_info": (
        "<target OID>",
        [
            1,  # suboid number one inside table
            2,  # suboid number two inside table
        ]),
}
