#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# <<<mysql_ha2>>>
# Instance db-name ha-name ha-group EstimatedDataLoss LogSendQueueSize LogSendRate RedoQueueSize RedoRate
# 

def inventory_mssql_ha2(info):
    for line in info:
        if len(line) > 1:
            yield line[0] + ' ' + line[1], None

def check_mssql_ha2(item, params, info):
    for line in info:
        if item != line[0] + ' ' + line[1]:
            continue
        if len(line) == 8:
            db_instance, db_name, ag_name, datalosstime, logsendqueue, logsendrate, redoqueue, redorate = line
        else:
            return 1, "Part of information missing from agent"
        state = 0
        infotext = "Possible dataloss is %s - Log queue size %s - Redo queue size %s" % (get_age_human_readable(int(datalosstime)), get_bytes_human_readable(int(logsendqueue)*1024), get_bytes_human_readable(int(redoqueue)*1024))
        perfdata = [("time", int(datalosstime)),("logqueue", int(logsendqueue)*1024),("redoqueue", int(redoqueue)*1024)]
        return state, infotext, perfdata

check_info["mssql_ha2"] = {
    'check_function'      : check_mssql_ha2,
    'inventory_function'  : inventory_mssql_ha2,
    'service_description' : 'AlwaysOn Database Replication %s',
    'has_perfdata'        : True,
}
