#!/usr/bin/env python3
'''Special agent command line configuration'''
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>

# License: GNU General Public License v2

from cmk.base.config import special_agent_info


def agent_macmon_arguments(params, hostname, ipaddress):
    '''build special agent command line'''
    arglist = ['--server', ipaddress or hostname]

    for param in ['port', 'username', 'password']:
        if param in params:
            arglist += [f'--{param}', f"{params[param]}"]

    return arglist


special_agent_info['macmon'] = agent_macmon_arguments
