#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# (c) Andreas Doehler <andreas.doehler@bechtle.com/andreas.doehler@gmail.com>
# License: GNU General Public License v2

# <<<netapp_api_bridges:sep(9)>>>
# status ok


def inventory_netapp_api_bridges(parsed):
    for bridge in parsed.keys():
        yield bridge, {}


def check_netapp_api_bridges(item, _no_params, parsed):
    data = parsed.get(item, {})

    if data.get("status"):
        state = 0 if data["status"].lower() in ["ok", "ok-with-suppressed", "ok_with_suppressed"
                                               ] else 2
        yield state, "Status: %s" % data["status"]


check_info["netapp_api_bridges"] = {
    'check_function': check_netapp_api_bridges,
    'inventory_function': inventory_netapp_api_bridges,
    'parse_function': lambda x: netapp_api_parse_lines(x),
    'service_description': 'Bridge %s',
    'includes': ["netapp_api.include"],
}
