#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_win_cert(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2( cmk.paths.local_agents_dir + "/windows/plugins/win_cert.ps1",
                     plugins_dir + "/win_cert.ps1")

        content = agent_file_header
        if "days" in conf:
            content += '$expireInDays = %d\n' % (int(conf['days']))
        if "issuer" in conf:
            content += '$issuerstring = "%s"\n' % (conf['issuer'])

        cfg_file = conf_dir + "/win_cert_cfg.ps1"
        content = content.replace('\n', '\r\n')
        file(cfg_file, "w").write(content)

bakery_info["win_cert"] = {
    "bake_function" : bake_win_cert,
    "os"            : [ "windows" ],
}

