#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_mssql_jobs(opsys, conf, conf_dir, plugins_dir):
    if conf:
        shutil.copy2(omd_root + "/local/share/check_mk/agents/windows/plugins/mssql_jobs.vbs",
                     plugins_dir + "/mssql_jobs.vbs")

bakery_info["mssql_jobs"] = {
    "bake_function" : bake_mssql_jobs,
    "os"            : [ "windows" ],
}

